title: Zachary Schoenberger # your name (or website title) here
logo: "/images/avatar.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data engineer and data analyst. My core languages are Python and R. I am also a practicing Cognos Analytics developer. My favorite projects focus on building automated solutions to data-intensive problems. My best asset is an ability and desire to learn new skills quickly, as needs arise.  
  <br><br>
  <a href="https://www.linkedin.com/in/zacharyschoenberger/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-167916938-1 # Google Analytics tracking ID
